import { NextResponse } from 'next/server';
import { getCurrentSession, hashPassword } from '@/lib/auth';
import { prisma } from '@/lib/db';
import { calculateAgreementSummary } from '@/lib/calculations';

export async function GET() {
  try {
    const session = await getCurrentSession();
    if (!session) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const whereCondition: any = {};
    if (session.role === 'SUPER_ADMIN') {
      // Super admin can see across all organizations
    } else if (session.role === 'ADMIN') {
      if (!session.organizationId) {
        return NextResponse.json({ error: 'Forbidden: User has no organization' }, { status: 403 });
      }
      whereCondition.organizationId = session.organizationId;
    } else {
      if (!session.organizationId) {
        return NextResponse.json({ error: 'Forbidden: Rider has no organization' }, { status: 403 });
      }
      whereCondition.organizationId = session.organizationId;
      whereCondition.hirerId = session.userId;
    }

    const agreements = await prisma.agreement.findMany({
      where: whereCondition,
      include: {
        hirer: {
          select: {
            id: true,
            name: true,
            phone: true,
            email: true,
          },
        },
        vehicle: true,
        payments: {
          orderBy: { datePaid: 'desc' },
        },
      },
      orderBy: { createdAt: 'desc' },
    });

    // Attach calculated financial summary to each agreement
    const agreementsWithSummary = agreements.map((agr) => {
      const summary = calculateAgreementSummary(agr);
      return {
        ...agr,
        summary,
      };
    });

    return NextResponse.json({ agreements: agreementsWithSummary });
  } catch (error) {
    console.error('Error fetching agreements:', error);
    return NextResponse.json({ error: 'Failed to fetch agreements' }, { status: 500 });
  }
}

export async function POST(request: Request) {
  try {
    const session = await getCurrentSession();
    if (!session || (session.role !== 'ADMIN' && session.role !== 'SUPER_ADMIN')) {
      return NextResponse.json({ error: 'Forbidden: Admin access required' }, { status: 403 });
    }

    if (!session.organizationId && session.role !== 'SUPER_ADMIN') {
      return NextResponse.json({ error: 'Forbidden: No organization assigned' }, { status: 403 });
    }

    const body = await request.json();
    const {
      organizationId: targetOrgId,
      ownerName,
      ownerPhone,
      hirerName,
      hirerPhone,
      hirerEmail,
      hirerPassword,
      guarantor1Name,
      guarantor1Phone,
      guarantor2Name,
      guarantor2Phone,
      makeModel,
      registrationNo,
      chassisNo,
      engineNo,
      colorYear,
      cashPrice,
      hirePurchasePrice,
      installmentAmount,
      frequency,
      totalInstallments,
      startDate,
    } = body;

    const orgId = session.role === 'SUPER_ADMIN' ? (targetOrgId || session.organizationId) : session.organizationId;

    if (!orgId) {
      return NextResponse.json({ error: 'Organization ID is required' }, { status: 400 });
    }

    // Validate required fields
    if (
      !ownerName ||
      !ownerPhone ||
      !hirerName ||
      !hirerPhone ||
      !makeModel ||
      !registrationNo ||
      !cashPrice ||
      !hirePurchasePrice ||
      !installmentAmount ||
      !totalInstallments ||
      !startDate
    ) {
      return NextResponse.json({ error: 'Missing required agreement or vehicle fields' }, { status: 400 });
    }

    // Server-side Ghana phone number validation (10 digits starting with 0)
    const { isValidGhanaPhone } = await import('@/lib/validation');
    if (!isValidGhanaPhone(ownerPhone)) {
      return NextResponse.json({ error: 'Owner phone number must be a valid 10-digit Ghana number starting with 0 (e.g. 0244123456)' }, { status: 400 });
    }

    if (!isValidGhanaPhone(hirerPhone)) {
      return NextResponse.json({ error: 'Hirer phone number must be a valid 10-digit Ghana number starting with 0 (e.g. 0244123456)' }, { status: 400 });
    }

    if (guarantor1Phone && !isValidGhanaPhone(guarantor1Phone)) {
      return NextResponse.json({ error: 'Guarantor 1 phone number must be a valid 10-digit Ghana number starting with 0 (e.g. 0208889900)' }, { status: 400 });
    }

    if (guarantor2Phone && !isValidGhanaPhone(guarantor2Phone)) {
      return NextResponse.json({ error: 'Guarantor 2 phone number must be a valid 10-digit Ghana number starting with 0 (e.g. 0554443322)' }, { status: 400 });
    }

    // 1. Find or Create Rider User Account
    let hirer = await prisma.user.findUnique({
      where: { phone: hirerPhone },
    });

    let assignedPassword = hirerPassword;
    let autoGeneratedPassword = false;

    if (!hirer) {
      if (!assignedPassword) {
        assignedPassword = 'WP-' + Math.random().toString(36).slice(-6).toUpperCase();
        autoGeneratedPassword = true;
      }

      const passwordHash = await hashPassword(assignedPassword);
      hirer = await prisma.user.create({
        data: {
          organizationId: orgId,
          name: hirerName,
          phone: hirerPhone,
          email: hirerEmail || null,
          passwordHash,
          role: 'RIDER',
          mustChangePassword: true,
        },
      });
    } else if (!hirer.organizationId) {
      // Connect existing user to organization
      await prisma.user.update({
        where: { id: hirer.id },
        data: { organizationId: orgId },
      });
    }

    // 2. Create Vehicle
    const vehicle = await prisma.vehicle.create({
      data: {
        organizationId: orgId,
        makeModel,
        registrationNo,
        chassisNo: chassisNo || null,
        engineNo: engineNo || null,
        colorYear: colorYear || null,
      },
    });

    // 3. Create Agreement
    const agreement = await prisma.agreement.create({
      data: {
        organizationId: orgId,
        ownerName,
        ownerPhone,
        hirerId: hirer.id,
        guarantor1Name: guarantor1Name || null,
        guarantor1Phone: guarantor1Phone || null,
        guarantor2Name: guarantor2Name || null,
        guarantor2Phone: guarantor2Phone || null,
        vehicleId: vehicle.id,
        cashPrice: parseFloat(cashPrice),
        hirePurchasePrice: parseFloat(hirePurchasePrice),
        installmentAmount: parseFloat(installmentAmount),
        frequency: frequency || 'WEEKLY',
        totalInstallments: parseInt(totalInstallments, 10),
        startDate: new Date(startDate),
        status: 'ACTIVE',
      },
      include: {
        hirer: true,
        vehicle: true,
      },
    });

    return NextResponse.json({
      agreement,
      assignedPassword: autoGeneratedPassword || hirerPassword ? assignedPassword : null,
      message: 'Agreement created successfully',
    });
  } catch (error) {
    console.error('Error creating agreement:', error);
    return NextResponse.json({ error: 'Failed to create agreement' }, { status: 500 });
  }
}
